EXTRA_CFLAGS = -DSCTM_INCLUDE=test.h -g "-I$(PWD)/include" -Wall -Werror -Wno-unused-function # "-Wno-unused-function" allows us to build the module sources separately
obj-m += blob.o # sctm.o
# sctm-obj += test.o

